---
- hosts: prod
  user: root
  vars_files:
    - vars/vars.yml

  tasks:

    - name: Create the deploy user
      user:
        name: "{{ deploy_user }}"
        state: present

    - name: Make the user a sudoer
      lineinfile:
        dest: "/etc/sudoers"
        state: present
        regexp: "^{{ deploy_user }}"
        line: "{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL"

    - name: Setup authorized key file for the deploy
      authorized_key:
        user: "{{ deploy_user }}"
        key:  "{{ ssh_keys_url }}"

    - name: Update SSH configuration to be more secure
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
        - { regexp: "^PermitRootLogin",        line: "PermitRootLogin no" }
        - { regexp: "^Port",                   line: "Port 2555" }
        - { regexp: "^AllowUsers",             line: "AllowUsers {{ deploy_user }}" }
      notify: Restart SSH

  handlers:

    - name: Restart SSH
      service:
        name: ssh
        state: restarted
